#R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

jdk:
 - oraclejdk8

env:
  global:
   -  NOT_CRAN="true"
  matrix:
    - SPARKLINGWATER_VERSION="2.3.4"
    - SPARKLINGWATER_VERSION="2.2.15"
    - SPARKLINGWATER_VERSION="2.1.29"
