#R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

jdk:
 - oraclejdk8

env:
  global:
   -  NOT_CRAN="true"
  matrix:
    - SPARKLINGWATER_VERSION="2.2.11"
    - SPARKLINGWATER_VERSION="2.1.25"
    - SPARKLINGWATER_VERSION="2.0.26"
    - SPARKLINGWATER_VERSION="1.6.13"